# Generated by Django 2.2.17 on 2020-12-25 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_ghgjhg'),
    ]

    operations = [
        migrations.AddField(
            model_name='ghgjhg',
            name='nhgnhgfhjg',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
