# Generated by Django 2.2.17 on 2020-12-25 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20201225_1407'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customtext',
            name='hjgjfhgjgh',
        ),
        migrations.RemoveField(
            model_name='customtext',
            name='jkhkjhkjhk',
        ),
        migrations.RemoveField(
            model_name='ghgjhg',
            name='nhgnhgfhjg',
        ),
    ]
